In [7]:
import numpy as np

print("---- Simple Attention Mechanism Explanation ------")

# Encoder outputs: 4 words, 2 features each
encoder_outputs = np.array([
    [0.1, 0.2],
    [0.5, 0.3],
    [0.2, 0.8],
    [0.9, 0.1]
])

print(f"\nEncoder Outputs (4 words, 2 features each):\n{encoder_outputs}")

# Decoder hidden state: what the decoder is currently looking for
decoder_hidden_state = np.array([0.8, 0.4])

print(f"\nDecoder hidden state (what we are looking for): {decoder_hidden_state}")

# Calculate alignment scores using dot product
alignment_scores = np.dot(encoder_outputs, decoder_hidden_state)

print(f"\nAlignment scores (similarity of each encoder output to decoder state):")
print(alignment_scores)


# Softmax function
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()


# Calculate attention weights
attention_weights = softmax(alignment_scores)

print(f"\nAttention weights (how much to 'pay attention' to each word):")
print(attention_weights)

print("\nNotice that the word at index 3 gets a high weight,")
print("meaning it is considered more relevant to the decoder's current state.")


# Calculate context vector
context_vector = np.sum(
    encoder_outputs * attention_weights[:, np.newaxis],
    axis=0
)

print(f"\nContext Vector (weighted combination of encoder outputs):")
print(context_vector)

---- Simple Attention Mechanism Explanation ------

Encoder Outputs (4 words, 2 features each):
[[0.1 0.2]
 [0.5 0.3]
 [0.2 0.8]
 [0.9 0.1]]

Decoder hidden state (what we are looking for): [0.8 0.4]

Alignment scores (similarity of each encoder output to decoder state):
[0.16 0.52 0.48 0.76]

Attention weights (how much to 'pay attention' to each word):
[0.17753866 0.25447139 0.24449342 0.32349653]

Notice that the word at index 3 gets a high weight,
meaning it is considered more relevant to the decoder's current state.

Context Vector (weighted combination of encoder outputs):
[0.48503512 0.33979354]
